language: ruby
rvm:
  - 2.0.0
  - 2.1
  - ruby-head
  - jruby-19mode
  - rbx-2
gemfile:
  - gemfiles/money_6.1.gemfile
  - gemfiles/money_6.2.gemfile
  - gemfiles/money_head.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
bundler_args: --without local_development
script:
  - mkdir tmp
  - bundle exec rake
